[project]
name = "Expenses"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bcrypt<4.1",
    "cyclopts>=4.22.2",
    "dotenv>=0.9.9",
    "fastapi>=0.141.1",
    "fastmcp>=3.4.5",
    "mysql-connector-python>=8.0.0",
    "passlib[bcrypt]>=1.7.4",
    "python-dotenv>=1.0.0",
    "python-jose>=3.5.0",
    "python-multipart>=0.0.32",
    "requests>=2.34.2",
]
